# Generated by Django 5.2.1 on 2025-06-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
