# Generated by Django 5.2.1 on 2025-06-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Diagnosis', 'Diagnosis'), ('Waiting Approval', 'Waiting Approval'), ('Waiting Parts', 'Waiting Parts'), ('In Progress', 'In Progress'), ('Ready for Pickup', 'Ready for Pickup'), ('Completed', 'Completed'), ('Invoiced', 'Invoiced'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('customer_complaint', models.TextField()),
                ('technician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='customers.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LABOR', 'Labor'), ('PART', 'Part')], max_length=10)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catalog_part', models.IntegerField(blank=True, null=True)),
                ('catalog_service', models.IntegerField(blank=True, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.workorder')),
            ],
        ),
    ]
