# Generated by Django 5.2.1 on 2025-06-09 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_is_active'),
        ('workorders', '0002_workorder_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='catalog_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_items', to='inventory.part'),
        ),
    ]
